name: last_fm
description: A simple app to demonstrate a good architecture with flutter_bloc, hive, and REST API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  functional_enum_annotation: ^1.2.3
  get_it: ^7.2.0
  go_router: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.1.1
  stream_transform: ^2.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  functional_enum: ^1.1.6
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mocktail: ^0.3.0

dependency_overrides:
  test_api: ^0.4.17

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_ios: "assets/images/icon_ios.png"
  image_path_android: "assets/images/icon_android.png"